apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../argocd/project-platform.yaml
  - ../../argocd/project-apps.yaml
  - ../../argocd/platform-dev.yaml
  - ../../argocd/boutique-lite-dev.yaml
