apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boutique-lite-dev

resources:
  - ../../base
  - httproute.yaml

images:
  - name: boutique-lite/adservice
    newName: ghcr.io/waeltarabishi/boutique-lite-adservice
    newTag: e841d7b8fc851096ea3385a161a49b84164ac292
  - name: boutique-lite/cartservice
    newName: ghcr.io/waeltarabishi/boutique-lite-cartservice
    newTag: e841d7b8fc851096ea3385a161a49b84164ac292
  - name: boutique-lite/checkoutservice
    newName: ghcr.io/waeltarabishi/boutique-lite-checkoutservice
    newTag: e841d7b8fc851096ea3385a161a49b84164ac292
  - name: boutique-lite/currencyservice
    newName: ghcr.io/waeltarabishi/boutique-lite-currencyservice
    newTag: e841d7b8fc851096ea3385a161a49b84164ac292
  - name: boutique-lite/emailservice
    newName: ghcr.io/waeltarabishi/boutique-lite-emailservice
    newTag: e841d7b8fc851096ea3385a161a49b84164ac292
  - name: boutique-lite/frontend
    newName: ghcr.io/waeltarabishi/boutique-lite-frontend
    newTag: e841d7b8fc851096ea3385a161a49b84164ac292
  - name: boutique-lite/paymentservice
    newName: ghcr.io/waeltarabishi/boutique-lite-paymentservice
    newTag: e841d7b8fc851096ea3385a161a49b84164ac292
  - name: boutique-lite/productcatalogservice
    newName: ghcr.io/waeltarabishi/boutique-lite-productcatalogservice
    newTag: e841d7b8fc851096ea3385a161a49b84164ac292
  - name: boutique-lite/recommendationservice
    newName: ghcr.io/waeltarabishi/boutique-lite-recommendationservice
    newTag: e841d7b8fc851096ea3385a161a49b84164ac292
  - name: boutique-lite/shippingservice
    newName: ghcr.io/waeltarabishi/boutique-lite-shippingservice
    newTag: e841d7b8fc851096ea3385a161a49b84164ac292
